%MATLAB Code from Sensor Array Analyzer App

%Generated by MATLAB 9.4 and Phased Array System Toolbox 3.6

%Generated on 05-Nov-2018 15:18:28

% Create a uniform rectangular array
h = phased.URA;
h.Size = [20 20];
h.ElementSpacing = [0.037974 0.037974];
h.Lattice = 'Rectangular';
h.ArrayNormal = 'x';
%Calculate Row Taper
sll = 25;
rwind = chebwin1(20, sll)';
rwind = repmat(rwind,20,1);
%Calculate Column Taper
sll = 25;
cwind = chebwin(20, sll)';
cwind = repmat(cwind.',1,20);
%Calculate taper
wind = rwind.*cwind;
h.Taper = wind;
%Create Cosine Antenna Element
el = phased.CosineAntennaElement;
el.CosinePower = [1 1];
h.Element = el;
%Assign steering angles, frequencies and propagation speed
SA = [18.5;0];
%Assign number of phase shift quantization bits
PS = 0;
F = 7900000000;
PS = 300000000;
%Create figure, panel, and axes
fig = figure;
panel = uipanel('Parent',fig);
hAxes = axes('Parent',panel,'Color','none');
%Calculate Steering Weights
w = zeros(getNumElements(h), length(F));
SV = phased.SteeringVector('SensorArray',h, 'PropagationSpeed', PS);
%Find the weights
for idx = 1:length(F)
    w(:, idx) = step(SV, F(idx), SA(:, idx));
end
%Plot 3d graph
fmt = 'polar';
pattern(h, F(1), 'PropagationSpeed', PS, 'Type','directivity', ...
    'CoordinateSystem', fmt,'weights', w(:,1));
%Adjust the view angles
view(hAxes,[86.0400000000001 -90]);
title = get(hAxes, 'title');
title_str = get(title, 'String');
%Modify the title
[Fval, ~, Fletter] = engunits(7900000000);
steeringString = 'steered at -10 Az, 0 El';
title_str = [title_str sprintf('\n') num2str(Fval) ' ' Fletter 'Hz ' ...
    steeringString];
set(title, 'String', title_str);
phases = angle(w);
figure(2);
plot(angle);
